packages:
  - "apps/web"
  - "apps/website"
  - "apps/desktop"
  - "packages/create-workframe"
  - "packages/workframe"
  - "packages/workframe-scoped"
  - "packages/workframe-core"
  - "services/workframe-api"
  - "services/workframe-supervisor"
