export { AppShell } from '@/components/shell/AppShell'
export { CanvasBackground } from '@/components/shell/CanvasBackground'
export { AtmosphereBg, DotGrid, MoleskineGrid } from '@/components/shell/canvas'
/** @deprecated Use CanvasBackground */
export { CanvasBackground as AtmosphereBackground } from '@/components/shell/CanvasBackground'
export { BrandMark } from '@/components/shell/BrandMark'
export { BrandTitle } from '@/components/shell/BrandTitle'
export { DesktopTitleBar } from '@/components/shell/DesktopTitleBar'
export { ShellHeader } from '@/components/shell/ShellHeader'
export { ShellNavLinks } from '@/components/shell/ShellNavLinks'
export { StageCard } from '@/components/shell/StageCard'
export { ThemeSwitcher } from '@/components/shell/ThemeSwitcher'
